POOL_SIZE = 4 
KERNEL_SIZE = 4
ACTIVATION_FUNC_1 = 'relu'
ACTIVATION_FUNC_2 = 'sigmoid'
ACTIVATION_FUNC_3 = 'tanh'
OUTPUT_FULL_MODEL_SHAPE = 5000
OUTPUT_MAIN_PEAK_MODEL_SHAPE = 1 
LOSS_MODEL = 'mean_absolute_error'